### ISSUE TITLE
Please add a license to the project

### ISSUE THREAD

**Issue by wlami** [playa-ru/keycloak-russian-providers#1]
I am interested in the project and would like to use and extend it if it had a permissive license. At its current state without any license mentioned usage by third parties is actually not possible.

**Comment by wlami** [comment]
Closing after one month of silence.

**Comment by hrensgory** [comment]
Hi, Wladislaw. Feel free to use it in any project or fork it. License file will be added soon.
Sorry for silence, we're too busy with oher projects.

**Comment by Argos92** [comment]
Added License Apache-2.0
