### ISSUE TITLE
Maybe mail.ru and vk.com have changed something?

### ISSUE THREAD

**Issue by camalsoft** [playa-ru/keycloak-russian-providers#12]
**VK:** 
ERROR [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (default task-419) Failed to make identity provider oauth callback: org.keycloak.broker.provider.IdentityBrokerException: No access token available in OAuth server response: {"error":"invalid_grant","error_description":"redirect_uri is invalid, please pass same redirect_uri, you used in authorize method."} at deployment.keycloak-russian-providers.jar//ru.playa.keycloak.modules.vk.VKIdentityProvider.getFederatedIdentity(VKIdentityProvider.java:120)

**Mail.ru:**
ERROR [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (default task-425) Failed to make identity provider oauth callback: org.keycloak.broker.provider.IdentityBrokerException: No access token available in OAuth server response: {"error":"token not found","error_code":6,"error_description":"token not found"}
        at org.keycloak.keycloak-services@15.0.2//org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider.getFederatedIdentity(AbstractOAuth2IdentityProvider.java:303)

**Yandex:** Ok

P.S. I have checked the settings several times.

**Comment by onotoliy** [comment]
**VK**
You specified correct redirect_uri (Доверенный redirect URI) in application?

![vk_provider_2](https://user-images.githubusercontent.com/10883059/155956238-49461255-9e60-4ddd-b419-1c97d789565b.png)

**Comment by onotoliy** [comment]
**Mail.ru**
We are aware of the problem. We'll fix it soon

**Comment by rootya802** [comment]
> **Mail.ru** Мы в курсе проблемы. Мы исправим это в ближайшее время

Vk работает отлично, с MailRu проблема, её не починили?

**Comment by onotoliy** [comment]
Добрый день. MailRu еще не подчинили, постараемся исправить в ближайшее время.

**Comment by camalsoft** [comment]
Совсем забыл уже про этот вопрос, всё работает. У vk была проблема с настройкой nginx перед keycloak (удивительно), а с mail.ru проблема вот какая интересная - почему-то старые (давно созданные) клиенты работают, а если создать свежий клиент в админке mail.ru - то ошибка

**Comment by camalsoft** [comment]
Дополню свой коммент: попробовал новый клиент через сутки и он работает

**Comment by onotoliy** [comment]
Работа Mail.RU восстановлена.
