### ISSUE TITLE
mail.ru identity provider - are there any options to restrict login only from certain email domains ?

### ISSUE THREAD

**Issue by GeminiQ1** [playa-ru/keycloak-russian-providers#17]
When using this provider, we encountered a situation that not only corporate mail accounts with a specific mail domain, but also any accounts with the @mail.ru domain can use it. Is there a way to add verification by mail domain for authorization somewhere?

**Comment by salemgolemugoo** [comment]
It works for Google Idp https://groups.google.com/g/keycloak-user/c/t6fv_XcGwZc. I would like to see this implementation also for Yandex mail

**Comment by onotoliy** [comment]
Добрый день. 
Добавлен список белых доменов для Yandex и Mail.RU в версии Keycloak 21.0.1
