### ISSUE TITLE
 Проблема при авторизации через VK

### ISSUE THREAD

**Issue by Timofei-gh** [playa-ru/keycloak-russian-providers#29]
День добрый. Прошу актуализировать инструкцию по интеграции библиотеки в keycloak под крайнюю версию. Сейчас не совсем корректно описаны пути до расположения тем.  
Столкнулся с проблемой при тестировании решения, что одной интеграции библиотеки недостаточно для успешной авторизации через ВК.  После анализа, увидел, что в кастомной сборке keycloak-russian, помимо прочего происходит замена org.keycloak.keycloak-admin-ui-21.1.1, как я понимаю именно это и добавляет необходимое поле API version форму создания /identity-providers/vk/add, что и приводит к успешной авторизации и создания пользователя в keycloak. Временно это решил, прописав в коде проваайдера конректную версию API.

**Comment by tsogto** [comment]
Cпасибо за сообщение, разбираемся.

**Comment by inver8** [comment]
Не только ВК, в ОК тоже надо дополнительно к стандартным client id и client secret прописывать еще публичный ключ, поле которое не отображается. Тему устанавливал как в readme написано, но дополнительные поля настроек провайдеров не появляются.

**Comment by Timofei-gh** [comment]
@inver8 в ОК не смотрел, но пока видимо 2 самых простых варианта.. 1. Хардкод нужного поля в самой либе русс. провайдеров.

**Comment by onotoliy** [comment]
Добрый день. 
Обновил документацию. 
Добавил блок с установкой новой admin-ui для Keycloak 21.1.1 - https://github.com/playa-ru/keycloak-russian-providers#keycloak--2111
