### ISSUE TITLE
Keycloak 10.0.0 support

### ISSUE THREAD

**Issue by zored** [playa-ru/keycloak-russian-providers#3]
I get "Resource not found..." when after adding any russian provider.

<details>
    <summary>Here are some warnings from logs</summary>
    12:37:21,040 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-2) WFLYSRV0027: Starting deployment of "keycloak-russian-providers-1.0.17.jar" (runtime-name: "keycloak-russian-providers-1.0.17.jar")<br/>
    12:37:21,337 WARN  [org.jboss.as.dependency.private] (MSC service thread 1-1) WFLYSRV0018: Deployment "deployment.keycloak-russian-providers-1.0.17.jar" is using a private module ("org.keycloak.keycloak-services") which may be changed or removed in future versions without notice.<br/>
    12:37:21,338 WARN  [org.jboss.as.dependency.private] (MSC service thread 1-1) WFLYSRV0018: Deployment "deployment.keycloak-russian-providers-1.0.17.jar" is using a private module ("org.keycloak.keycloak-server-spi-private") which may be changed or removed in future versions without notice.<br/>
    12:37:21,348 INFO  [org.keycloak.subsystem.server.extension.KeycloakProviderDeploymentProcessor] (MSC service thread 1-1) Deploying Keycloak provider: keycloak-russian-providers-1.0.17.jar<br/>
    12:37:21,428 WARN  [org.keycloak.services] (MSC service thread 1-1) KC-SERVICES0047: yandex (ru.playa.keycloak.modules.yandex.YandexIdentityProviderFactory) is implementing the internal SPI social. This SPI is internal and may change without notice<br/>
    12:37:21,429 WARN  [org.keycloak.services] (MSC service thread 1-1) KC-SERVICES0047: vk (ru.playa.keycloak.modules.vk.VKIdentityProviderFactory) is implementing the internal SPI social. This SPI is internal and may change without notice<br/>
    12:37:21,429 WARN  [org.keycloak.services] (MSC service thread 1-1) KC-SERVICES0047: ok (ru.playa.keycloak.modules.ok.OKIdentityProviderFactory) is implementing the internal SPI social. This SPI is internal and may change without notice<br/>
    12:37:21,429 WARN  [org.keycloak.services] (MSC service thread 1-1) KC-SERVICES0047: mailru (ru.playa.keycloak.modules.mailru.MailRuIdentityProviderFactory) is implementing the internal SPI social. This SPI is internal and may change without notice<br/>
    12:37:21,455 WARN  [org.keycloak.services] (MSC service thread 1-1) KC-SERVICES0047: yandex-user-attribute-mapper (ru.playa.keycloak.modules.yandex.YandexUserAttributeMapper) is implementing the internal SPI identity-provider-mapper. This SPI is internal and may change without notice<br/>
    12:37:21,456 WARN  [org.keycloak.services] (MSC service thread 1-1) KC-SERVICES0047: vk-user-attribute-mapper (ru.playa.keycloak.modules.vk.VKUserAttributeMapper) is implementing the internal SPI identity-provider-mapper. This SPI is internal and may change without notice<br/>
    12:37:21,457 WARN  [org.keycloak.services] (MSC service thread 1-1) KC-SERVICES0047: ok-user-attribute-mapper (ru.playa.keycloak.modules.ok.OKUserAttributeMapper) is implementing the internal SPI identity-provider-mapper. This SPI is internal and may change without notice<br/>
    12:37:21,467 WARN  [org.keycloak.services] (MSC service thread 1-1) KC-SERVICES0047: mailru-user-attribute-mapper (ru.playa.keycloak.modules.mailru.MailRuUserAttributeMapper) is implementing the internal SPI identity-provider-mapper. This SPI is internal and may change without notice<br/>
    12:37:21,819 INFO  [org.jboss.as.server] (DeploymentScanner-threads - 2) WFLYSRV0010: Deployed "keycloak-russian-providers-1.0.17.jar" (runtime-name : "keycloak-russian-providers-1.0.17.jar")
</details>

**Comment by onotoliy** [comment]
Thanks for your report, we investigation this exceptions.

**Comment by onotoliy** [comment]
Thanks for your report.

[Instruction for install keycloak-russian-providers](https://github.com/playa-ru/keycloak-russian-providers/blob/master/readme_en.md#without-docker)

Have you copied the files `/src/main/resources/theme/base/admin/resources/partials` to `${keycloak.home.dir}/themes/base/admin/resources/partials` ?
