### ISSUE TITLE
Update to Keycloak 22.*

### ISSUE THREAD

**Issue by sw1tchdev** [playa-ru/keycloak-russian-providers#30]
Hello, thx for plugin. Keycloak 22.* can't start with version `21.1.1-rsp` of this plugin because [transition-from-java-ee-to-jakarta-ee](https://www.keycloak.org/docs/latest/upgrading/index.html#transition-from-java-ee-to-jakarta-ee) with error:

```
[org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-11) Uncaught server error: java.lang.NoClassDefFoundError: javax/ws/rs/WebApplicationException
```

I'll try to make a PR soon 🙂

**Comment by onotoliy** [comment]
Thank you very much for your report. We are aware of the problem and will issue a release soon.

**Comment by sw1tchdev** [comment]
Thank you too, also you can see my solution in this PR #31
