### ISSUE TITLE
Актуальность кэширования стейтов в VKIDIdentityProvider

### ISSUE THREAD

**Issue by vgilko** [playa-ru/keycloak-russian-providers#37]
Привет!
Подскажите, для чего мы кэшируем стейт в [VKIDIdentityProvider](https://github.com/playa-ru/keycloak-russian-providers/blob/5f65c772f6e29db32b4aa248a179ff0c6072ead6/src/main/java/ru/playa/keycloak/modules/vkid/VKIDIdentityProvider.java#L50)?

```
    /**
     * Кеш state-ов.
     */
    private static final Map<String, String> CACHE = new HashMap<>();
```

Разве без него нельзя обойтись? Параметр `OAUTH2_PARAMETER_STATE` как раз описывает стейт, по которому мы можем получить из КК связанную с ним сессию

**Comment by onotoliy** [comment]
Здравствуйте. 
Нет не обойтись. 
При генерации URL авторизации нужно передать не state, а UUID - это требование VK ID.
