### ISSUE TITLE
Ошибка при логине через VK ID

### ISSUE THREAD

**Issue by nikitxskv** [playa-ru/keycloak-russian-providers#38]
Спасибо за плагины!
Но у меня не получается настроить логин через vk id
Есть ли инструкция?
Указываю ID приложения и Защищённый ключ в качестве Client ID и Client Secret
Но получаю вот такую ошибку..
<img width="427" alt="Screenshot 2024-06-13 at 23 43 07" src="https://github.com/playa-ru/keycloak-russian-providers/assets/9549626/93697a1c-63f5-4eb3-bb43-1d1ed3c00a5a">
<img width="1440" alt="Screenshot 2024-06-13 at 23 54 07" src="https://github.com/playa-ru/keycloak-russian-providers/assets/9549626/0ab72e03-d305-4234-b716-8502df58c57b">

**Comment by onotoliy** [comment]
Актуальная версия библиотеки для Keycloak 24.0.1 - 24.0.1.rsp-2
При настройках:
![Screenshot_8](https://github.com/playa-ru/keycloak-russian-providers/assets/10883059/dc126624-a8e3-4572-ac94-becb12bbb2d3)
Авторизация работает без ошибок. Пример [тут](https://my.yachtex.ru)
