### ISSUE TITLE
Логин через VK ID 

### ISSUE THREAD

**Issue by exister** [playa-ru/keycloak-russian-providers#40]
Спасибо за плагин!

При использование архивного [silent token](https://id.vk.com/about/business/go/docs/ru/vkid/archive/1.0.0/vk-id/tokens/silent-token) происходит ошибка "Redirection URL does not contain a state parameter".

Версия 24.0.1.rsp-2

**Comment by onotoliy** [comment]
Добрый день. Попробуйте версию 24.0.1.rsp-3.
