### ISSUE TITLE
VKID - Генерируется неверный урл для авторизации 

### ISSUE THREAD

**Issue by sashok2k** [playa-ru/keycloak-russian-providers#45]
Пробую настроить с использованием 25.0.2.rsp-1, однако генерируется ссылка в которой не участвует code_verifier и device_id.

такое ощущение что генерируется ссылка с параметрами старого VK OAuth. Может это быть как то связано с настройками KeyCloak?

`https://id.vk.com/authorize?scope=&state=IbGJZRlChxoRFpq7oIQ9UHghRjEkaUd1TB3xylFL27g.KZOQwqH3vQA.m1NmbrKOQV6aYXT8UKjRNQ&response_type=code&client_id=yyyy&redirect_uri=xxxx`

Немного посмотрел на код, выглядит так что взывается метод абстрактного `AbstractOAuth2IdentityProvider`

**Comment by sashok2k** [comment]
Ктонибудь?

**Comment by onotoliy** [comment]
Добрый день.
В провайдере реализовано два варианта входа:
1. VK - это старый VK OAuth
2. VKID - это новый VKID протокол

Вы какой из них настроили?

Вот тут проставляется device_id и code_verifier:
https://github.com/playa-ru/keycloak-russian-providers/blob/14bf19f8c68134f8d43fb12ed1b6952da6fa4886/src/main/java/ru/playa/keycloak/modules/vkid/VKIDEndpoint.java#L107

**Comment by onotoliy** [comment]
Процесс авторизации происходит следующими шагами:
1. Открытие формы в VK ID
`https://id.vk.com/authorize?response_type=code&client_id=12345&scope=email%20phone&redirect_uri=https%3A%2F%2Fyour.site&state=XXXRandomZZZ&code_challenge=K8KAyQ82WSEncryptedVerifierGYUDj8K&code_challenge_method=s256`
2. После входа придет `device_id` и `code_verifier`
3. Обмен кода на токен. Тут мы передаем `device_id` и `code_verifier`.

Документация по VK ID: https://id.vk.com/about/business/go/docs/ru/vkid/latest/vk-id/connection/start-integration/auth-without-sdk/auth-without-sdk-web
