### ISSUE TITLE
Is it possible to use prompt=select_account for yandex?

### ISSUE THREAD

**Issue by thdonatello** [playa-ru/keycloak-russian-providers#47]
Привет!
Подскажите, как можно заставить провайдера спрашивать yandex аккаунт?
Поймал типичную проблему, что имея более одного аккаунта (войдя, например, в личный и рабочий), провайдер автоматически авторизует под одним из них и никогда не предлагает выбора. Единственный вариант - выйти из Я-аккаунтов.

**Comment by thdonatello** [comment]
Поизучал немного проблему. В настройках google провайдера имеется специальное поле `prompt`, позволяющее задать этот параметр. Так же параметр `Hosted Domain`, передающий `hd=<domain>` в yandex провайдере этого не делает.

**Comment by paragor** [comment]
Тоже столкнулся с проблемой, что у пользователя может быть несколько аккаунтов.
Яндекс говорит, что необходимо использовать login_hint и/или force_confirm: https://yandex.ru/dev/id/doc/ru/codes/code-url#optional

На данный момент я не вижу способа прокинуть эти параметры. Но очень хотелось бы их видеть в конфиге провайдера.

P.S. Hosted Domain - это параметр, который уже на стороне keycloak не дает пройти невалидным доменам
https://github.com/playa-ru/keycloak-russian-providers/blob/master/src/main/java/ru/playa/keycloak/modules/yandex/YandexIdentityProvider.java#L86

**Comment by paragor** [comment]
скрин подтверждающий, что фича позволяет выбрать аккаунт в яндексе 
![telegram-cloud-photo-size-2-5251346046716601372-y](https://github.com/user-attachments/assets/d1194a43-d1d2-4c86-93ae-0032a9fea841)
