### ISSUE TITLE
Сообщение "identityProviderEmailErrorMessage"

### ISSUE THREAD

**Issue by dmitrymalinin** [playa-ru/keycloak-russian-providers#5]
Выдаёт сообщение "identityProviderEmailErrorMessage" при попытке входа через ОК
[keycloak-russian-providers-Fixed-identityProviderEmailErrorMessage.patch.txt](https://github.com/playa-ru/keycloak-russian-providers/files/4744730/keycloak-russian-providers-Fixed-identityProviderEmailErrorMessage.patch.txt)
[keycloak-russian-providers-Fixed-identityProviderEmailErrorMessage-2.patch.txt](https://github.com/playa-ru/keycloak-russian-providers/files/4744787/keycloak-russian-providers-Fixed-identityProviderEmailErrorMessage-2.patch.txt)

**Comment by hrensgory** [comment]
Спасибо, в ближайшее время посмотрим патчи и, скорее всего, вольём их.

**Comment by onotoliy** [comment]
Добрый день, т.к. нужен перевод текста ошибки - это решение не правильное.
Надо сделать следующее:
* В файл `${keycloak.home.dir}/theme/base/login/messages/messages_en.properties` добавьте следующие строки:
```
identityProviderEmailErrorMessage=For authorization through a social network, you must specify your e-mail in your social network profile.
```
* В файл `${keycloak.home.dir}/theme/base/login/messages/messages_ru.properties` добавьте следующие строки:
```
identityProviderEmailErrorMessage=Для авторизации через социальную сеть необходимо в Вашем профиле соц. сети указать Ваш e-mail.
```

Описание установки провайдеров обновил.

**Comment by dmitrymalinin** [comment]
... только всё равно выдаёт сообщение "We are sorry ... identityProviderEmailErrorMessage"

**Comment by dmitrymalinin** [comment]
Заработало! Спасибо.
