### ISSUE TITLE
Настройка emailRequired для OK и VK

### ISSUE THREAD

**Issue by dmitrymalinin** [playa-ru/keycloak-russian-providers#6]
Позволяет отключить exception при отсутствии email. Чтобы была возможность войти без email в профиле, или если соцсеть не выдаёт email
[Настройка-emailRequired-для-ОК-и-VK.patch.txt](https://github.com/playa-ru/keycloak-russian-providers/files/4746463/-emailRequired-.-.-.-VK.patch.txt)

**Comment by hrensgory** [comment]
Спасибо, в ближайшее время посмотрим и, скорее всего, вольём.

**Comment by onotoliy** [comment]
Спасибо большое, patch принят в версиях выше 1.0.42.
