### ISSUE TITLE
Формирование brokerUserName в случае отсутствия email

### ISSUE THREAD

**Issue by dmitrymalinin** [playa-ru/keycloak-russian-providers#7]
Чтобы в Federated Identities поле не пустое было, если username и email нет (для ОК)
[Формирование-brokerUserName-в-случае-отсутствия-emai.patch.txt](https://github.com/playa-ru/keycloak-russian-providers/files/4750825/-brokerUserName-.-.-.-emai.patch.txt)

**Comment by onotoliy** [comment]
Спасибо большое, patch принят в версиях выше 1.0.42.
