### ISSUE TITLE
Keycloak 13.0.0 support

### ISSUE THREAD

**Issue by dafanasiev** [playa-ru/keycloak-russian-providers#8]
Keycloak team change internal API, so now (for keycloak version >13) keycloak-russian-providers compilation fails.

**Comment by onotoliy** [comment]
Use the following versions of keycloak-russian-providers

- 1.0.43 for Keycloak 17.0.0
- 1.0.42 for Keycloak 16.1.1
- 1.0.38 for Keycloak 15.0.2
- 1.0.37 for Keycloak 13.0.0
